# Generated by Django 5.0.1 on 2025-06-08 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TODO', 'To Do'), ('DOING', 'Doing'), ('DONE', 'Done')], default='TODO', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Uma descrição breve do status.', null=True)),
            ],
            options={
                'verbose_name': 'Status do Projeto',
                'verbose_name_plural': 'Status dos Projetos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome do Projeto')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects_management.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-start_date', 'name'],
            },
        ),
    ]
